### PR TITLE
Remove gpg-pubkey packages from RPM lists.

### PR DESCRIPTION
**Pull request by csams**
Signed-off-by: Christopher Sams <csams@redhat.com>

### CODE REVIEW

**Review by CodeHeeler — APPROVED** [review]
This looks great, thanks for splitting these out into the other methods and making the whole thing cleaner and more correct.  Tests, too, awesome!

**Comment by CodeHeeler** [comment]
Related PRs:
https://github.com/RedHatInsights/inventory-schemas/pull/58
https://github.com/RedHatInsights/insights-host-inventory/pull/857

**Comment by CodeHeeler** [comment]
@SteveHNH I'm not sure why this is failing; is this a separate clowder/env issue again?

**Comment by SteveHNH** [comment]
@CodeHeeler 
Sorry for the delay getting around to this one. This actually looks like a bad string comparison in `installed_packages` may have been introduced.

**Pull request merged**
