### PR TITLE
Add model name as cpu_model to system profile

### PR DESCRIPTION
**Pull request by CodeHeeler**
Add model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39

### CODE REVIEW

**Comment by SteveHNH** [comment]
@CodeHeeler this is good to go from my end. Does inventory need to get something merged first?

**Comment by CodeHeeler** [comment]
Spoke with Tahmid about it because I thought puptoo had to go first, but he thinks letting schema merge first makes the most sense so they can quickly revert if there are issues with the definition.  I'll ping once that is merged.  Thanks for asking!

**Comment by CodeHeeler** [comment]
Rebased at Brandon Squizzato's suggestion to see if that fixes the failing ephemeral env on this PR. @SteveHNH ^

**Comment by CodeHeeler** [comment]
@SteveHNH cpu_model has made it to prod in inventory; this can be merged now.

**Pull request merged**
