### PR TITLE
RHINENG-1520: add public_dns to system_profile for AWS

### PR DESCRIPTION
**Pull request by xiangce**

### CODE REVIEW

**Comment by xiangce** [comment]
The local test looks good
```
    os_release              : '9.2'
    public_dns              : ['ec2-10-10-10-10.eu-north-1.compute.amazonaws.com']
    public_ipv4_addresses   : ['10.10.10.10']
```

**Review by r14chandra — APPROVED** [review]
Thanks for working on this @xiangce!
The PR looks good to me 👍🏻

**Comment by xiangce** [comment]
@r14chandra - Thanks a lot for the review.

**Pull request merged**
