### PR TITLE
RHINENG-416 & RHIN-822 - exclude function_instances from SAP workloads and use `instances` attribute

### PR DESCRIPTION
**Pull request by r14chandra**

### CODE REVIEW

**Review by kgaikwad — COMMENTED** [review]
@r14chandra, with this change tests are not happy! 
Need modifications to IQE Puptoo tests that based on `sap_system`.
Current job failure:
```

17:21:38         host_sp = json.loads(response.data)["results"][0]["system_profile"]
17:21:38         assert "sap" in host_sp
17:21:38 >       assert host_sp["sap"]["sap_system"] is True
17:21:38 E       assert False is True
17:21:38 
17:21:38 /iqe_venv/lib/python3.9/site-packages/iqe_puptoo/tests/test_archive_process.py:147: AssertionError
```

**Comment by r14chandra** [comment]
The PR is not for review. We need some customer ack first.

**Comment by strider** [comment]
Hi @r14chandra @kgaikwad,

I am working on RHINENG-2286[Remove SAP-related fields from System Profile on inventory-schemas] and I was modifying the puptoo code to not rely anymore on those old SAP-related fields. And I stumbled upon this PR which is kind of touching the same part I was working on. Would it be interesting to take advantage of this PR to get rid of the them or do you prefer a follow up PR?

Thanks,
Gaël

**Comment by r14chandra** [comment]
> Hi @r14chandra @kgaikwad,
> 
> I am working on RHINENG-2286[Remove SAP-related fields from System Profile on inventory-schemas] and I was modifying the puptoo code to not rely anymore on those old SAP-related fields. And I stumbled upon this PR which is kind of touching the same part I was working on. Would it be interesting to take advantage of this PR to get rid of the them or do you prefer a follow up PR?
> 
> Thanks, Gaël

Hello @strider ,
I don't really know when this PR will be good for review and get merged. 
It would be good if we handle the required changes for removing the sap-related fields in the separate PR.

**Comment by xiangce** [comment]
@r14chandra - lgtm

**Pull request merged**
