### PR TITLE
Add HDB version parser and files

### PR DESCRIPTION
**Pull request by SteveHNH**
This is to get the sap_version back into the system_proflie

### CODE REVIEW

**Comment by SteveHNH** [comment]
This one uses our HDB parser to grab the version. It matches the schema we had setup forever ago. Looks like it does the job.

**Review by beav — APPROVED** [review]

**Comment by beav** [comment]
not sure if this error is the root cause or a cascading error

```

16:46:10 Recording test results
16:46:10 ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
```

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks for getting back to this work.

**Comment by SteveHNH** [comment]
> 
> 
> not sure if this error is the root cause or a cascading error
> 
> ```
> 
> 16:46:10 Recording test results
> 16:46:10 ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
> ```

That keeps happening. I think it's something up with the testing env.

**Pull request merged**
