### PR TITLE
Dual support for clowder and legacy

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by kylape** [comment]
```diff --git a/pr_check.sh b/pr_check.sh
index 700693f..e70de3c 100755
--- a/pr_check.sh
+++ b/pr_check.sh
@@ -80,4 +80,4 @@ bonfire namespace wait-on-resources $NAMESPACE
 
 # Spin up iqe pod
 python utils/create_iqe_pod.py $NAMESPACE
-oc rsh -n $NAMESPACE iqe-tests curl -si http://puptoo:9000/metrics
+oc rsh -n $NAMESPACE iqe-tests curl -si http://puptoo-puptoo:9000/metrics
```

**Comment by kylape** [comment]
Please merge once you get the tests passing. We identified a bug with bonfire where it needs to wait to mark a namespace as ready after it deploys a ClowdEnv to give it time to settle the env-specific deployments.  The point being that you may need to run the tests a few times before they pass.

**Comment by psav** [comment]
> ```diff
> index 700693f..e70de3c 100755
> --- a/pr_check.sh
> +++ b/pr_check.sh
> @@ -80,4 +80,4 @@ bonfire namespace wait-on-resources $NAMESPACE
>  
>  # Spin up iqe pod
>  python utils/create_iqe_pod.py $NAMESPACE
> -oc rsh -n $NAMESPACE iqe-tests curl -si http://puptoo:9000/metrics
> +oc rsh -n $NAMESPACE iqe-tests curl -si http://puptoo-puptoo:9000/metrics
> ```

Thanks for the reminder on this - I went ahead and renamed the pod so that we end up with the nice names we spoke of `puptoo-processor`

**Comment by psav** [comment]
I don't have merge access - but it's passing :)

**Pull request merged**
