### PR TITLE
DRFT-33 - pass all packages not only max

### PR DESCRIPTION
**Pull request by CodeHeeler**
This is in addition to the "installed_packages" not instead of.

### CODE REVIEW

**Comment by CodeHeeler** [comment]
We're passing installed_packages using get_max, so now we need "everything else" which I'm here calling "all_remaining_installed_packages" but I'm open to other suggestions.  Then Drift can recombine the two to get all packages, which we need, without breaking anyone else using the existing subset.

**Comment by beav** [comment]
The field name seems OK to me given that 'all_packages' already exists (and is a misnomer)

**Comment by beav** [comment]
This appears to have  a failing test

```

16:33:05 MainThread ERROR insights-puptoo - System Profile failed due to installed_packages encountering an error: 'str' object has no attribute 'nevra'
16:33:05 System_profile failure: 'Unknown component: puptoo.process.system_profile'
```

**Comment by CodeHeeler** [comment]
Updated the name to installed_packages_delta as per today's discussion

**Comment by SteveHNH** [comment]
looks good to me!

**Pull request merged**
