### PR TITLE
Add a check for AWS Marketplace

### PR DESCRIPTION
**Pull request by SteveHNH**
Adding a check for marketplace codes in a system. If they exist, we mark this system as a marketplace one in system_profile

JIRA: RHCLOUD-12089

### CODE REVIEW

**Comment by SteveHNH** [comment]
looks like my "format on save" function caught a bunch of stuff in this PR as well. Just FYI @CodeHeeler

**Review by CodeHeeler — APPROVED** [review]
Yeah, I figured you ran a linter or something that caught the old quotation issues.  Looks good to me.  Thanks!

**Comment by CodeHeeler** [comment]
Is the build failure another ephemeral env failure like we ran into on another PR recently?

**Comment by SteveHNH** [comment]
> 
> 
> Is the build failure another ephemeral env failure like we ran into on another PR recently?

Looks like it. I'll ping the devprod team and see if we can figure out why this keeps happening

**Comment by SteveHNH** [comment]
This one isn't in prod yet for inventory. Going to need to wait until that happens.

**Pull request merged**
